version: '3.8'
services:
  customer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - customer_db
    volumes:
      - .:/app
  customer_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: customer
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33070:3306



