version: '3.8'
services:
  product:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - product_db
    volumes:
      - .:/app
  product_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: product
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33072:3306




